### ISSUE TITLE
Set Up Your Kanban Board

### ISSUE THREAD

**Issue by Itswali** [Itswali/capstoneProject2#17]
# Link for PROJECT.
https://github.com/Itswali/capstoneProject2/projects/3
* Wali Muhammad [Student A]
* Utsargo Roy [Student B]

**Comment by mukhammadrizooff** [comment]
Hi @TEAM, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

<img src="https://media4.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Highlights
- Good implementations ✔️ 

## Required Changes ♻️
- [ ] [REQUIRED] Good job so far! All cards should be assigned to team members. You should see a circle with the user's avatar on each card please 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/210272372-a890654a-1df0-4557-b9ed-76ac8a12c459.png)

- [ ] [REQUIRED] Please add `Team members` Names to the issue's description because it should have information about the `number` of `people` in your `group` 🙏🏼 

![image](https://user-images.githubusercontent.com/63915024/210272476-9bed71ab-ece8-4b38-b8ce-2342129b2542.png)


## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by uwadonat** [comment]
## Hi @Team,

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
### Congratulations! 🎉 
### Highlights
- Cards were assigned to team members in a fair way ✔️

# Status: Approved ✔️✔️✔️

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100%.
Please, remember to tag me @uwadonat in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
```
